fixed dynamic shadows

diff --git a/.github/workflows/libserum.yml b/.github/workflows/libserum.yml
--- a/.github/workflows/libserum.yml
+++ b/.github/workflows/libserum.yml
@@ -25,10 +25,19 @@ jobs:
           VERSION_PATCH=$(grep -Eo "SERUM_VERSION_PATCH\s+[0-9]+" src/serum-version.h | grep -Eo "[0-9]+")
           VERSION_CONCENTRATE=$(grep -Eo "SERUM_CONCENTRATE_VERSION\s+[0-9]+" src/serum-version.h | grep -Eo "[0-9]+")
           SERUM_VERSION="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}"
-          TAG="${SERUM_VERSION}-concentrate-${VERSION_CONCENTRATE}"
+          TAG="${SERUM_VERSION}-concentrate.${VERSION_CONCENTRATE}"
           echo "${TAG}"
           echo "tag=${TAG}" >> $GITHUB_OUTPUT
           echo "serumversion=${SERUM_VERSION}" >> $GITHUB_OUTPUT
+      - name: Check git tag
+        if: startsWith(github.ref, 'refs/tags/v')
+        run: |
+          GIT_TAG="${GITHUB_REF#refs/tags/}"
+          EXPECTED_TAG="v${{ steps.version.outputs.tag }}"
+          if [[ "${GIT_TAG}" != "${EXPECTED_TAG}" ]]; then
+            echo "Error: Git tag (${GIT_TAG}) does not match version from serum-version.h (v${{ steps.version.outputs.tag }})"
+            exit 1
+          fi
 
   build:
     name: Build libserum-${{ matrix.platform }}-${{ matrix.arch }}
